/**
 * Tool definitions for Imagen image editing.
 * These tools allow the LLM to edit images generated by Imagen 4.
 */

import type { ToolDefinition } from "./tool-definitions";

export const IMAGEN_EDIT_TOOLS: ToolDefinition[] = [
  {
    name: "imagen_crop",
    description:
      "Crop an image to a specific rectangular region. Use this when the user wants to focus on part of an image or remove edges. IMPORTANT: When the user says 'crop this image', 'crop the image', or similar phrases referring to the currently displayed image, use imageId: 'current'. The 'current' imageId refers to the image currently displayed in the Image Generation view.",
    parameters: {
      type: "object",
      properties: {
        imageId: {
          type: "string",
          description:
            "ID of the image to crop. ALWAYS use 'current' when the user refers to 'this image', 'the image', 'the current image', or when an image is displayed in the Image Generation view. You can also use a specific image ID if provided.",
        },
        x: {
          type: "number",
          description:
            "X coordinate of the top-left corner of the crop region (in pixels)",
        },
        y: {
          type: "number",
          description:
            "Y coordinate of the top-left corner of the crop region (in pixels)",
        },
        width: {
          type: "number",
          description: "Width of the crop region (in pixels)",
        },
        height: {
          type: "number",
          description: "Height of the crop region (in pixels)",
        },
      },
      required: ["imageId", "x", "y", "width", "height"],
    },
  },
  {
    name: "imagen_resize",
    description:
      "Resize an image to specific dimensions. Use this when the user wants to change the size of an image. IMPORTANT: When the user says 'resize this image', 'make this smaller/larger', or similar phrases referring to the currently displayed image, use imageId: 'current'.",
    parameters: {
      type: "object",
      properties: {
        imageId: {
          type: "string",
          description:
            "ID of the image to resize. ALWAYS use 'current' when the user refers to 'this image', 'the image', 'the current image', or when an image is displayed in the Image Generation view.",
        },
        width: {
          type: "number",
          description: "Target width in pixels",
        },
        height: {
          type: "number",
          description: "Target height in pixels",
        },
        maintainAspectRatio: {
          type: "boolean",
          description: "Whether to maintain aspect ratio (default: true)",
        },
      },
      required: ["imageId", "width", "height"],
    },
  },
  {
    name: "imagen_adjust",
    description:
      "Adjust image properties like brightness, contrast, saturation, and hue. Use this when the user wants to improve or modify the appearance of an image. IMPORTANT: When the user says 'brighten this', 'darken this', 'increase contrast', 'make it more vibrant', or similar phrases referring to the currently displayed image, use imageId: 'current'.",
    parameters: {
      type: "object",
      properties: {
        imageId: {
          type: "string",
          description:
            "ID of the image to adjust. ALWAYS use 'current' when the user refers to 'this image', 'the image', 'the current image', or when an image is displayed in the Image Generation view.",
        },
        brightness: {
          type: "number",
          description:
            "Brightness adjustment (0.5 to 2.0, where 1.0 is no change). Values > 1.0 make brighter, < 1.0 make darker. Default: 1.0",
        },
        contrast: {
          type: "number",
          description:
            "Contrast adjustment (0.5 to 2.0, where 1.0 is no change). Values > 1.0 increase contrast. Default: 1.0",
        },
        saturation: {
          type: "number",
          description:
            "Saturation adjustment (0.0 to 2.0, where 1.0 is no change). 0.0 = grayscale, > 1.0 = more vibrant. Default: 1.0",
        },
        hue: {
          type: "number",
          description: "Hue rotation in degrees (0-360). Default: 0",
        },
      },
      required: ["imageId"],
    },
  },
  {
    name: "imagen_filter",
    description:
      "Apply visual filters or effects to an image. Use this when the user wants to change the style or add effects like blur, sharpen, grayscale, etc. IMPORTANT: When the user says 'blur this image', 'blur the image', 'blur it', 'apply blur', or similar phrases referring to the currently displayed image, you MUST use this tool with imageId: 'current' and filter: 'blur'. The 'current' imageId refers to the image currently displayed in the Image Generation view (50/50 split view).",
    parameters: {
      type: "object",
      properties: {
        imageId: {
          type: "string",
          description:
            "ID of the image to filter. ALWAYS use 'current' when the user refers to 'this image', 'the image', 'the current image', or when an image is displayed in the Image Generation view. The 'current' imageId automatically resolves to the image shown in the 50/50 split view. You can also use a specific image ID if provided.",
        },
        filter: {
          type: "string",
          enum: ["blur", "sharpen", "grayscale", "sepia", "negate", "threshold"],
          description: "Type of filter to apply. Use 'blur' when the user asks to blur the image.",
        },
        intensity: {
          type: "number",
          description:
            "Filter intensity (0-100). For blur: radius in pixels (higher = more blur). For sharpen: strength. Default: 50. For blur effects, typical values are 10-30 for subtle blur, 30-50 for moderate blur, 50-100 for strong blur.",
        },
      },
      required: ["imageId", "filter"],
    },
  },
  {
    name: "imagen_rotate",
    description:
      "Rotate or flip an image. Use this when the user wants to change the orientation. IMPORTANT: When the user says 'rotate this image', 'flip this', or similar phrases referring to the currently displayed image, use imageId: 'current'.",
    parameters: {
      type: "object",
      properties: {
        imageId: {
          type: "string",
          description:
            "ID of the image to rotate. ALWAYS use 'current' when the user refers to 'this image', 'the image', 'the current image', or when an image is displayed in the Image Generation view.",
        },
        angle: {
          type: "number",
          description: "Rotation angle in degrees (90, 180, 270)",
        },
        flip: {
          type: "string",
          enum: ["horizontal", "vertical", "both"],
          description:
            "Flip direction (optional, alternative to rotation)",
        },
      },
      required: ["imageId"],
    },
  },
  {
    name: "imagen_format",
    description:
      "Convert image format (PNG, JPEG, WebP, etc.). Use this when the user wants to change the file format. IMPORTANT: When the user says 'convert this to PNG/JPEG', or similar phrases referring to the currently displayed image, use imageId: 'current'.",
    parameters: {
      type: "object",
      properties: {
        imageId: {
          type: "string",
          description:
            "ID of the image to convert. ALWAYS use 'current' when the user refers to 'this image', 'the image', 'the current image', or when an image is displayed in the Image Generation view.",
        },
        format: {
          type: "string",
          enum: ["png", "jpeg", "jpg", "webp", "avif"],
          description: "Target format",
        },
        quality: {
          type: "number",
          description: "Quality for lossy formats (1-100). Default: 80",
        },
      },
      required: ["imageId", "format"],
    },
  },
];

